removed obsolete code, and modified tests to better reflect new endpoints

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -37,28 +37,6 @@ jobs:
         run: |
           npx wait-on http-get://localhost:3000/about --timeout 30000
 
-      - name: POST /login (wrong password)
-        run: |
-          STATUS=$(curl -s -o /dev/null -X POST "http://localhost:3000/login" -H "Content-Type: application/json" -d '{"username":"r.rose","password":"12345"}' -w %{http_code})
-
-          if [ "$STATUS" != "401" ]; then
-            echo "Expected 401, got $STATUS"
-            exit 1
-          else
-            echo "$STATUS"
-          fi
-
-      - name: POST /login (wrong username)
-        run: |
-          STATUS=$(curl -s -o /dev/null -X POST "http://localhost:3000/login" -H "Content-Type: application/json" -d '{"username":"w.schnee","password":"1234"}' -w %{http_code})
-
-          if [ "$STATUS" != "401" ]; then
-            echo "Expected 401, got $STATUS"
-            exit 1
-          else
-            echo "$STATUS"
-          fi
-
       - name: POST /login (existing)
         run: |
           curl --fail -X POST "http://localhost:3000/login" -H "Content-Type: application/json" -d '{"username": "r.rose", "password":"1234"}'
@@ -70,6 +48,28 @@ jobs:
       - name: POST /login (new)
         run: |
           curl --fail -X POST "http://localhost:3000/login" -H "Content-Type: application/json" -d '{"username": "penny", "password": "robot87284"}'
+
+      - name: POST /login (wrong password)
+        run: |
+          STATUS=$(curl -s -o /dev/null -X POST "http://localhost:3000/login" -H "Content-Type: application/json" -d '{"username":"penny","password":"robot12345"}' -w %{http_code})
+
+          if [ "$STATUS" != "401" ]; then
+            echo "Expected 401, got $STATUS"
+            exit 1
+          else
+            echo "$STATUS"
+          fi
+
+      - name: POST /login (wrong username)
+        run: |
+          STATUS=$(curl -s -o /dev/null -X POST "http://localhost:3000/login" -H "Content-Type: application/json" -d '{"username":"w.schnee","password":"robot87284"}' -w %{http_code})
+
+          if [ "$STATUS" != "401" ]; then
+            echo "Expected 401, got $STATUS"
+            exit 1
+          else
+            echo "$STATUS"
+          fi
 
       - name: POST /signup (duplicate username)
         run: |
@@ -93,13 +93,14 @@ jobs:
             echo "$STATUS"
           fi
 
-      - name: POST /signup-string
-        run: |
-          curl --fail -X POST "http://localhost:3000/signup-string" -H "Content-Type: application/json" -d '{"id": 3, "username": "n.valkyrie", "password": "iLoveHammers"}'
+      # The following tests existed before alphanumeric support for passwords.
+      # - name: POST /signup-string
+      #   run: |
+      #     curl --fail -X POST "http://localhost:3000/signup-string" -H "Content-Type: application/json" -d '{"id": 3, "username": "n.valkyrie", "password": "iLoveHammers"}'
 
-      - name: POST /login-string
-        run: |
-          curl --fail -X POST "http://localhost:3000/login-string" -H "Content-Type: application/json" -d '{"username": "n.valkyrie", "password":"iLoveHammers"}'
+      # - name: POST /login-string
+      #   run: |
+      #     curl --fail -X POST "http://localhost:3000/login-string" -H "Content-Type: application/json" -d '{"username": "n.valkyrie", "password":"iLoveHammers"}'
 
       - name: stop server
         if: always()
